<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class NewsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '4',
            'position_image_news' => 'beforeTitle',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'AfterText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value',
            'title' => 'Título Value',
            'call' => 'Chamada Value',
            'text' => 'Texto Value',
            'journalist_font' => 'Jornalista/Fronte Value',
            'url_email' => 'URL/E-mail Value',
            'tags' => 'Tags Value',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(1)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'highlights',
            'banner_desktop_id' => '4',
            'banner_mobile_id' => '4',
            'image_news_id' => '5',
            'position_image_news' => 'AfterText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeTitle',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(2)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'geral',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(3)
         ]);
         DB::table('news')->insert([
            'type_news' => 'audio',
            'position_news' => 'geral',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(4)
         ]);
         DB::table('news')->insert([
            'type_news' => 'text',
            'position_news' => 'geral',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(5)
         ]);
         DB::table('news')->insert([
            'type_news' => 'video',
            'position_news' => 'highlights',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(6)
         ]);
         DB::table('news')->insert([
            'type_news' => 'audio',
            'position_news' => 'highlights',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(7)
         ]);
         DB::table('news')->insert([
            'type_news' => 'text',
            'position_news' => 'highlights',
            'banner_desktop_id' => '4',
            'banner_mobile_id' => '4',
            'image_news_id' => '4',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(8)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'AfterText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=IP6Swz8Oss1Cs3oI',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeText',
            'start_date' => '2023-10-07 16:20:00',
            'end_date' => '2024-02-29 16:20:00',
            'topper' => 'Cartola Value 2 Banner',
            'title' => 'Título Value 2 Banner',
            'call' => 'Chamada Value 2 Banner',
            'text' => 'Texto Value 2 Banner',
            'journalist_font' => 'Jornalista/Fonte Value 2 Banner',
            'url_email' => 'Url/E-mail Value 2 Banner',
            'tags' => 'Tags Value 2 Banner',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(9)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeTitle',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'AfterText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value',
            'title' => 'Título Value',
            'call' => 'Chamada Value',
            'text' => 'Texto Value',
            'journalist_font' => 'Jornalista/Fronte Value',
            'url_email' => 'URL/E-mail Value',
            'tags' => 'Tags Value',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(10)
        ]);

        DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '4',
            'banner_mobile_id' => '4',
            'image_news_id' => '4',
            'position_image_news' => 'beforeTitle',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'AfterText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value',
            'title' => 'Título Value',
            'call' => 'Chamada Value',
            'text' => 'Texto Value',
            'journalist_font' => 'Jornalista/Fronte Value',
            'url_email' => 'URL/E-mail Value',
            'tags' => 'Tags Value',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(1)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'highlights',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'AfterText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeTitle',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(2)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'geral',
            'banner_desktop_id' => '3',
            'banner_mobile_id' => '3',
            'image_news_id' => '3',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(3)
         ]);
         DB::table('news')->insert([
            'type_news' => 'audio',
            'position_news' => 'geral',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(4)
         ]);
         DB::table('news')->insert([
            'type_news' => 'text',
            'position_news' => 'geral',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(5)
         ]);
         DB::table('news')->insert([
            'type_news' => 'video',
            'position_news' => 'highlights',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(6)
         ]);
         DB::table('news')->insert([
            'type_news' => 'audio',
            'position_news' => 'highlights',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(7)
         ]);
         DB::table('news')->insert([
            'type_news' => 'text',
            'position_news' => 'highlights',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(8)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'AfterText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=IP6Swz8Oss1Cs3oI',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeText',
            'start_date' => '2023-10-07 16:20:00',
            'end_date' => '2024-02-29 16:20:00',
            'topper' => 'Cartola Value 2 Banner',
            'title' => 'Título Value 2 Banner',
            'call' => 'Chamada Value 2 Banner',
            'text' => 'Texto Value 2 Banner',
            'journalist_font' => 'Jornalista/Fonte Value 2 Banner',
            'url_email' => 'Url/E-mail Value 2 Banner',
            'tags' => 'Tags Value 2 Banner',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(9)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeTitle',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'AfterText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value',
            'title' => 'Título Value',
            'call' => 'Chamada Value',
            'text' => 'Texto Value',
            'journalist_font' => 'Jornalista/Fronte Value',
            'url_email' => 'URL/E-mail Value',
            'tags' => 'Tags Value',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(10)
        ]);

        DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '4',
            'banner_mobile_id' => '4',
            'image_news_id' => '4',
            'position_image_news' => 'beforeTitle',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'AfterText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value',
            'title' => 'Título Value',
            'call' => 'Chamada Value',
            'text' => 'Texto Value',
            'journalist_font' => 'Jornalista/Fronte Value',
            'url_email' => 'URL/E-mail Value',
            'tags' => 'Tags Value',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(1)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'highlights',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'AfterText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeTitle',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(2)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'geral',
            'banner_desktop_id' => '13',
            'banner_mobile_id' => '13',
            'image_news_id' => '13',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(3)
         ]);
         DB::table('news')->insert([
            'type_news' => 'audio',
            'position_news' => 'geral',
            'banner_desktop_id' => '3',
            'banner_mobile_id' => '3',
            'image_news_id' => '3',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(4)
         ]);
         DB::table('news')->insert([
            'type_news' => 'text',
            'position_news' => 'geral',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(5)
         ]);
         DB::table('news')->insert([
            'type_news' => 'video',
            'position_news' => 'highlights',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(6)
         ]);
         DB::table('news')->insert([
            'type_news' => 'audio',
            'position_news' => 'highlights',
            'banner_desktop_id' => '4',
            'banner_mobile_id' => '4',
            'image_news_id' => '4',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(7)
         ]);
         DB::table('news')->insert([
            'type_news' => 'text',
            'position_news' => 'highlights',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(8)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'AfterText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=IP6Swz8Oss1Cs3oI',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeText',
            'start_date' => '2023-10-07 16:20:00',
            'end_date' => '2024-02-29 16:20:00',
            'topper' => 'Cartola Value 2 Banner',
            'title' => 'Título Value 2 Banner',
            'call' => 'Chamada Value 2 Banner',
            'text' => 'Texto Value 2 Banner',
            'journalist_font' => 'Jornalista/Fonte Value 2 Banner',
            'url_email' => 'Url/E-mail Value 2 Banner',
            'tags' => 'Tags Value 2 Banner',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(9)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeTitle',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'AfterText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value',
            'title' => 'Título Value',
            'call' => 'Chamada Value',
            'text' => 'Texto Value',
            'journalist_font' => 'Jornalista/Fronte Value',
            'url_email' => 'URL/E-mail Value',
            'tags' => 'Tags Value',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(10)
        ]);

        DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '4',
            'banner_mobile_id' => '4',
            'image_news_id' => '4',
            'position_image_news' => 'beforeTitle',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'AfterText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value',
            'title' => 'Título Value',
            'call' => 'Chamada Value',
            'text' => 'Texto Value',
            'journalist_font' => 'Jornalista/Fronte Value',
            'url_email' => 'URL/E-mail Value',
            'tags' => 'Tags Value',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(1)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'highlights',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'AfterText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeTitle',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(2)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'geral',
            'banner_desktop_id' => '13',
            'banner_mobile_id' => '13',
            'image_news_id' => '13',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(3)
         ]);
         DB::table('news')->insert([
            'type_news' => 'audio',
            'position_news' => 'geral',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(4)
         ]);
         DB::table('news')->insert([
            'type_news' => 'text',
            'position_news' => 'geral',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(5)
         ]);
         DB::table('news')->insert([
            'type_news' => 'video',
            'position_news' => 'highlights',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(6)
         ]);
         DB::table('news')->insert([
            'type_news' => 'audio',
            'position_news' => 'highlights',
            'banner_desktop_id' => '4',
            'banner_mobile_id' => '4',
            'image_news_id' => '4',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(7)
         ]);
         DB::table('news')->insert([
            'type_news' => 'text',
            'position_news' => 'highlights',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(8)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'AfterText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=IP6Swz8Oss1Cs3oI',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeText',
            'start_date' => '2023-10-07 16:20:00',
            'end_date' => '2024-02-29 16:20:00',
            'topper' => 'Cartola Value 2 Banner',
            'title' => 'Título Value 2 Banner',
            'call' => 'Chamada Value 2 Banner',
            'text' => 'Texto Value 2 Banner',
            'journalist_font' => 'Jornalista/Fonte Value 2 Banner',
            'url_email' => 'Url/E-mail Value 2 Banner',
            'tags' => 'Tags Value 2 Banner',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(9)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'banner',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeTitle',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'AfterText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value',
            'title' => 'Título Value',
            'call' => 'Chamada Value',
            'text' => 'Texto Value',
            'journalist_font' => 'Jornalista/Fronte Value',
            'url_email' => 'URL/E-mail Value',
            'tags' => 'Tags Value',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(10)
        ]);



        DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'geral',
            'banner_desktop_id' => '4',
            'banner_mobile_id' => '4',
            'image_news_id' => '4',
            'position_image_news' => 'beforeTitle',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'AfterText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value',
            'title' => 'Título Value',
            'call' => 'Chamada Value',
            'text' => 'Texto Value',
            'journalist_font' => 'Jornalista/Fronte Value',
            'url_email' => 'URL/E-mail Value',
            'tags' => 'Tags Value',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(1)
         ]);

         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'geral',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'AfterText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeTitle',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(2)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'geral',
            'banner_desktop_id' => '13',
            'banner_mobile_id' => '13',
            'image_news_id' => '13',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(3)
         ]);
         DB::table('news')->insert([
            'type_news' => 'audio',
            'position_news' => 'geral',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(4)
         ]);
         DB::table('news')->insert([
            'type_news' => 'text',
            'position_news' => 'geral',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Geral',
            'title' => 'Título Value Geral',
            'call' => 'Chamada Value Geral',
            'text' => 'Texto Value Geral',
            'journalist_font' => 'Jornalista/Fronte Value Geral',
            'url_email' => 'URL/E-mail Value Geral',
            'tags' => 'Tags Value Geral',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(5)
         ]);
         DB::table('news')->insert([
            'type_news' => 'video',
            'position_news' => 'geral',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(6)
         ]);
         DB::table('news')->insert([
            'type_news' => 'audio',
            'position_news' => 'geral',
            'banner_desktop_id' => '4',
            'banner_mobile_id' => '4',
            'image_news_id' => '4',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(7)
         ]);
         DB::table('news')->insert([
            'type_news' => 'text',
            'position_news' => 'geral',
            'banner_desktop_id' => '1',
            'banner_mobile_id' => '1',
            'image_news_id' => '1',
            'position_image_news' => 'beforeText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'AfterText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeTitle',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-31 14:10:00',
            'topper' => 'Cartola Value Destaque',
            'title' => 'Título Value Destaque',
            'call' => 'Chamada Value Destaque',
            'text' => 'Texto Value Destaque',
            'journalist_font' => 'Jornalista/Fronte Value Destaque',
            'url_email' => 'URL/E-mail Value Destaque',
            'tags' => 'Tags Value Destaque',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(8)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'geral',
            'banner_desktop_id' => '5',
            'banner_mobile_id' => '5',
            'image_news_id' => '5',
            'position_image_news' => 'AfterText',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=IP6Swz8Oss1Cs3oI',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'beforeText',
            'start_date' => '2023-10-07 16:20:00',
            'end_date' => '2024-02-29 16:20:00',
            'topper' => 'Cartola Value 2 Banner',
            'title' => 'Título Value 2 Banner',
            'call' => 'Chamada Value 2 Banner',
            'text' => 'Texto Value 2 Banner',
            'journalist_font' => 'Jornalista/Fonte Value 2 Banner',
            'url_email' => 'Url/E-mail Value 2 Banner',
            'tags' => 'Tags Value 2 Banner',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(9)
         ]);
         DB::table('news')->insert([
            'type_news' => 'image',
            'position_news' => 'geral',
            'banner_desktop_id' => '2',
            'banner_mobile_id' => '2',
            'image_news_id' => '2',
            'position_image_news' => 'beforeTitle',
            'video_news' => 'https://www.youtube.com/live/siN7p6s9HWM?si=uVN8nscaaBVGrxNP',
            'position_video_news' => 'beforeText',
            'audio_news_id' => '6',
            'position_audio_news' => 'AfterText',
            'start_date' => '2023-10-06 14:15:00',
            'end_date' => '2023-10-12 14:10:00',
            'topper' => 'Cartola Value',
            'title' => 'Título Value',
            'call' => 'Chamada Value',
            'text' => 'Texto Value',
            'journalist_font' => 'Jornalista/Fronte Value',
            'url_email' => 'URL/E-mail Value',
            'tags' => 'Tags Value',
            'instagram' => null,
            'facebook' => null,
            'twitter' => null,
            'whatsapp' => null,
            'created_at' => Carbon::now()->addSecond(10)
        ]);
    }
}
